alg_name: DINM
model_name: Qwen1.5-7B  # the vanilla LLM path  
model_class: AutoModelForCausalLM
tokenizer_class: AutoTokenizer
device: 0



suffix_system_prompt: "If the user's request is reasonable, give the correct answer. Please give the right response:"

# You can specify the edited layer for all data in advance, for example: layer: [31]
# DINM locates the toxic layer for each instance in safety_editour.py
layers: [4, 5, 6, 7, 8] # MEMIT
num_steps: 10
batch_size: 1
max_length: 2048
max_output_length: 200
lr: 1e-5
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: 'model.layers.{}.mlp.down_proj.weight'
layer_module_tmp: 'model.layers.{}'
mlp_module_tmp: 'model.layers.{}.mlp'
attn_module_tmp: 'model.layers.{}.self_attn'
ln_f_module: 'model.norm'
lm_head_module: 'lm_head'
model_parallel: false
bf16: true
