alg_name: "LoRA"
model_name: "/home/lyc/TNTprojectz/LLM/huggingface/gpt-j-6b"
data_path: "/home/lyc/TNTprojectz/KE/EasyEdit/dataset/portability/One Hop/"
data_file: "zsre_mend_eval_portability_gpt4.json"
torch_dtype: ""
load_in_8bit: true
CUDA_VISIBLE_DEVICES: "2,3"
device: 2
model_parallel: false
layers: [3,4,5,6,7,8]
num_steps: 30
batch_size: 20
max_length: 30
lr: 5e-3
weight_decay: 0
kl_factor: 0
rank: 16
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["fc_out"]  